image: python:3.9

stages:
  - build
  - test
  - coverage

build-job:
  stage: build
  script:
    - pip install -r requirements.txt 

test-job:
  stage: test
  script:
    - FASTAPI_ENV=test coverage run -m uvicorn src.main:app &
    - curl -Lo mapi https://mayhem4api.forallsecure.com/downloads/cli/latest/linux-musl/mapi && chmod +x mapi
    - ./mapi login $MAPI_TOKEN
    - ./mapi run forallsecure/mapi-action-examples auto "http://localhost:8000/openapi.json" --url "http://localhost:8000/" --junit junit.xml --sarif mapi.sarif --html mapi.html
    - pgrep python3 | xargs kill || true
  artifacts:
    when: always
    paths:
      - junit.xml
      - mapi.html
      - mapi.sarif
      - .coverage
    reports:
      junit: junit.xml

coverage-report:
  stage: coverage
  needs: ["test-job"]
  script:
    - coverage combine  # Combine coverage data if there are multiple .coverage files
    - coverage report
    - coverage xml
    - coverage html -d coverage_html_report
  artifacts:
    when: always
    paths:
      - coverage_html_report/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
