// First job
pipeline {
    agent {
        docker { image 'python:3.9' }
    }
    
    environment {
        MAYHEM_URL = 'https://app.mayhem.security'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh '''
                      cd /workspace
                      pip install -r requirements.txt 
                   '''
            }
        }
        stage('Start API') {
            steps {
                echo 'Building..'
                sh '''
                      cd /workspace
                      FASTAPI_ENV=test python3 -m coverage run -m uvicorn src.main:app &
                   '''
            }
        }
        stage('Scan') {
            steps {
                script {
                    try {
                        echo 'Scanning..'
                        sh '''
                              curl -Lo mapi ${MAYHEM_URL}/cli/mapi/linux-musl/latest/mapi && chmod +x mapi
                           '''
                        withCredentials([string(credentialsId: 'MAYHEM_TOKEN', variable: 'MAYHEM_TOKEN')]) {
                            sh '''
                                    ./mapi login ${MAYHEM_TOKEN}
                                    ./mapi run forallsecure-demo/mapi-action-examples/fastapi auto "http://localhost:8000/openapi.json" --url "http://localhost:8000/" --junit junit.xml --sarif mapi.sarif --html mapi.html
                               '''
                        }
                    } finally {
                        /* Kill python if it's still running, ignoring any errors */
                        sh 'pgrep python3 | xargs kill || true'

                        /* Generate coverage report */
                        sh 'python3 -m coverage xml -o coverage.xml || true'
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Archive and Code coverage....'
            archiveArtifacts artifacts: 'junit.xml, mapi.sarif, mapi.html, coverage.xml',
                allowEmptyArchive: true,
                fingerprint: true,
                onlyIfSuccessful: false
            junit 'junit.xml'
            recordIssues(enabledForFailure: true,
                         tool: sarif(pattern: 'mapi.sarif'))
            recordCoverage(tools: [[parser: 'COBERTURA', pattern: 'coverage.xml']], 
                         sourceCodeRetention: 'LAST_BUILD')
        }
    }
}
