name: 'Mayhem for API on Jenkins'
on:
  push:
    branches: [ main, jenkins-example ]
  pull_request:
    branches: [ main, jenkins-example ]
  workflow_dispatch:



jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Jenkins job'
        uses:
          jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: jenkins/Jenkinsfile
          pluginstxt: jenkins/plugins.txt
        env:
          MAYHEM_URL: 'https://app.mayhem.security'
          MAYHEM_TOKEN: ${{ secrets.MAYHEM_TOKEN }}
        
