name: 'Mayhem for API'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Download Mayhem for API CLI for linux (also available for windows and MAC
    - name: Download API fuzzer CLI
      run: |
        curl -s -LO https://mayhem4api.forallsecure.com/downloads/cli/latest/linux-musl/mapi
        chmod +x ./mapi

    # Create environment to run API
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Run API in test mode. We configured test mode to output stacktraces in
    # the error responses to improve the output of Mayhem for API.
    - name: Run API
      env:
        FASTAPI_ENV: test
      run: uvicorn src.main:app &

    # Run Mayhem for API
    - name: Mayhem for API Scan
      env:
        MAPI_TOKEN: ${{ secrets.MAPI_TOKEN }}
      run: ./mapi run fastapi 10 --url http://localhost:8000/ --sarif results.sarif --html results.html http://localhost:8000/openapi.json || true

    # Archive HTML report
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: mapi-report
        path: results.html

    # Upload SARIF file (only available on public repos or github enterprise)
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

